### ISSUE TITLE
После того как закрыть плеер и запустить снова песню вылетает из приложения

### ISSUE THREAD

**Issue by glin94** [Zeratyll/flutter_background_audio#1]

**Comment by N9vn1njdf** [comment]
Можете дать логи?

**Comment by glin94** [comment]
необязательно  ли в массиве song ключом ссылка на аудио должна быть строка source? как плеер находит ссылку?

**Comment by N9vn1njdf** [comment]
source может быть как URL ссылка так и путь к файлу

**Comment by glin94** [comment]
имею ввиду если у меня ключ не строка 'source', а другая , я беру данные в формате json
обязательно ли чтобы ключ назывался "source"?

**Comment by N9vn1njdf** [comment]
Да, ключ должен быть source. Можешь пройтись циклом по json и создать ключ source.
Например так
```
json.forEach((map) {
   map['source'] = map['url'];
});
```

**Comment by glin94** [comment]
хорошо, спасибо за плагин. Он лучший!

**Comment by glin94** [comment]
еще вопрос, обязательно ли чтобы id c 1 начинался?

**Comment by N9vn1njdf** [comment]
> хорошо, спасибо за плагин. Он лучший!

Пожалуйста)

> еще вопрос, обязательно ли чтобы id c 1 начинался?

Нет, это доп поле, которое никак не используется плагином. Плагину нужно обязательно только три поля author, title, source. Остальные данные можно добавлять по своему усмотрению - как например id.

**Comment by glin94** [comment]
Если author нет, то не будет работать? у меня только три поля url,title и id(

**Comment by N9vn1njdf** [comment]
Отправь пустое значение. Дополню пример выше
```
json.forEach((map) {
   map['source'] = map['url'];
   map['author'] = ' ';
});
```

**Comment by glin94** [comment]
хорошо)

**Comment by glin94** [comment]
а поле metadata обязательно должна быть заполнено?

**Comment by N9vn1njdf** [comment]
Нет, оно для доп полей плейлиста. Например название плейлиста или еще что.

**Comment by glin94** [comment]
проблема в том что я включаю трек, в панели для уведомлений плеер выходит название песни тоже есть только песня не играет(

**Comment by N9vn1njdf** [comment]
Скрин можно?

**Comment by glin94** [comment]
![image](https://user-images.githubusercontent.com/34025626/50297858-d6601900-048e-11e9-9cb3-dd78e78c603a.png)

**Comment by N9vn1njdf** [comment]
Извини я бы помог, но у меня очень много дел. Это проблема твоего кода или баг плагина? Если второе, то я постараюсь его исправить как освобожусь

**Comment by glin94** [comment]
это я прошу прощения за свою тупость, спасибо еще раз тебе, ты мне очень помог. все работает)

**Comment by glin94** [comment]
> Извини я бы помог, но у меня очень много дел. Это проблема твоего кода или баг плагина? Если второе, то я постараюсь его исправить как освобожусь

**Comment by glin94** [comment]
Хотел спросить, этот плагин для iOS подойдёт?

**Comment by N9vn1njdf** [comment]
Нет. только для android

**Comment by hajiparvane** [comment]
@glin94 @Zeratyll   У меня такая же проблема .
'После того как закрыть плеер и запустить снова песню вылетает из приложения'
Как было решено?
