### ISSUE TITLE
Ios Problem

### ISSUE THREAD

**Issue by flashomer** [Zeratyll/flutter_background_audio#6]
Hi, i try for ios because it's not work.

Error VsCode:
http://prntscr.com/o5dzto

Error log Xcode: 
`2019-06-22 22:29:09.433751+0300 Runner[1186:25106] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
2019-06-22 22:29:09.434550+0300 Runner[1186:25106] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
2019-06-22 22:29:09.569837+0300 Runner[1186:25501] flutter: Observatory listening on http://127.0.0.1:49290/K4QU9fJUHS0=/
2019-06-22 22:29:10.372402+0300 Runner[1186:25496] flutter: BackgroundAudio: Added listener "onTogglePlayback"
2019-06-22 22:29:10.377024+0300 Runner[1186:25496] flutter: BackgroundAudio: Added listener "onDuration"
2019-06-22 22:29:10.379101+0300 Runner[1186:25496] flutter: BackgroundAudio: Added listener "onPosition"
2019-06-22 22:29:10.380663+0300 Runner[1186:25496] flutter: BackgroundAudio: Added listener "onNext"
2019-06-22 22:29:10.382242+0300 Runner[1186:25496] flutter: BackgroundAudio: Added listener "onPrev"
2019-06-22 22:29:10.383546+0300 Runner[1186:25496] flutter: BackgroundAudio: Added listener "onSelect"
2019-06-22 22:29:10.385749+0300 Runner[1186:25496] flutter: BackgroundAudio: Added listener "onStop"
2019-06-22 22:29:11.922723+0300 Runner[1186:25496] [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method getOptions on channel method_channel)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
<asynchronous suspension>
#1      BackgroundAudio.init (package:background_audio/background_audio.dart:46:20)
<asynchronous suspension>
#2      _MyAppState.initState (package:background_audio_example/main.dart:30:21)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#7      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:933:16)
#8      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:904:5)
#9      RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:850:17)
#10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2258:19)
#11     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:849:13)
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
#13     runApp (package:flutter/src/widgets/binding.dart:780:7)
#14     main (package:background_audio_example/main.dart:4:16)
#15     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:199:25)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1500:12)
#20     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:190:5)
#21     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
2019-06-22 22:29:11.931176+0300 Runner[1186:25496] [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method getPlaylist on channel method_channel)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
<asynchronous suspension>
#1      BackgroundAudio.init (package:background_audio/background_audio.dart:52:37)
#2      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#3      BackgroundAudio.init (package:background_audio/background_audio.dart:45:14)
#4      _MyAppState.initState (package:background_audio_example/main.dart:30:21)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
#9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:933:16)
#10     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:904:5)
#11     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:850:17)
#12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2258:19)
#13     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:849:13)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
#15     runApp (package:flutter/src/widgets/binding.dart:780:7)
#16     main (package:background_audio_example/main.dart:4:16)
#17     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:199:25)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1500:12)
#22     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:190:5)
#23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
2019-06-22 22:29:14.114316+0300 Runner[1186:25496] [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method setPlaylist on channel method_channel)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
<asynchronous suspension>
#1      BackgroundAudio.setPlaylist (package:background_audio/background_audio.dart:86:28)
<asynchronous suspension>
#2      _MyAppState.play (package:background_audio_example/main.dart:92:27)
<asynchronous suspension>
#3      _MyAppState._buildPlaylist.<anonymous closure>.<anonymous closure> (package:background_audio_example/main.dart:108:30)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
#7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
#8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:211:7)
#9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:225:20)
#11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#15     _rootRunUnary (dart:async/zone.dart:1136:13)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#18     _invoke1 (dart:ui/hooks.dart:233:10)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
2019-06-22 22:29:15.793061+0300 Runner[1186:25496] [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method play on channel method_channel)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
<asynchronous suspension>
#1      BackgroundAudio.play (package:background_audio/background_audio.dart:116:26)
<asynchronous suspension>
#2      _MyAppState.play (package:background_audio_example/main.dart:93:21)
<asynchronous suspension>
#3      _MyAppState._buildPlaylist.<anonymous closure>.<anonymous closure> (package:background_audio_example/main.dart:108:30)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
#7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
#8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:211:7)
#9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:225:20)
#11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#15     _rootRunUnary (dart:async/zone.dart:1136:13)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#18     _invoke1 (dart:ui/hooks.dart:233:10)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)`

**Comment by serikasilan** [comment]
Yeah I taking the same error please fix it

**Comment by RamazanIpek** [comment]
Yes ı have same problem. If you fix this issue, I will thankful

**Comment by N9vn1njdf** [comment]
Hello. Plugin does not support iOS. I can't fix it
